name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9.4
  - numpy=1.20.1
  - scipy=1.6.2
  - pandas=1.2.4
  - matplotlib=3.4.2
  - pip
  - pip:
    - ndmath==0.0.5
    - openplaning==0.1.2
    - pymoo==0.4.2.2
