name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - numpy=1.21.2
  - scipy=1.7.1
  - pandas=1.3.3
  - matplotlib=3.4.3
  - pip
  - pip:
    - ndmath==0.0.5
    - openplaning==0.2.0
    - pymoo==0.5.0
